name: inaturalistjs CI

on: [push, pull_request]

jobs:
  pre_build:
    runs-on: ubuntu-18.04
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}

  build:
    needs: pre_build
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - run: npm install

    - run: npm test

    - run: npm run coveralls
      if: env.COVERALLS_REPO_TOKEN != null
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

  notify:
    name: Notify Slack
    needs: build
    if: ${{ success() || failure() }}
    runs-on: ubuntu-18.04
    steps:
      - uses: iRoachie/slack-github-actions@v2.0.1
        if: env.SLACK_WEBHOOK_URL != null
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BUILDS_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
